/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadHistoryRouteImport } from './routes/upload-history'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as StockAnalysisRouteImport } from './routes/stock-analysis'
import { Route as SlowMovingRouteImport } from './routes/slow-moving'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PurchaseRecommendationsRouteImport } from './routes/purchase-recommendations'
import { Route as HighPriorityStockRouteImport } from './routes/high-priority-stock'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItemsItemIdRouteImport } from './routes/items.$itemId'

const UploadHistoryRoute = UploadHistoryRouteImport.update({
  id: '/upload-history',
  path: '/upload-history',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const StockAnalysisRoute = StockAnalysisRouteImport.update({
  id: '/stock-analysis',
  path: '/stock-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const SlowMovingRoute = SlowMovingRouteImport.update({
  id: '/slow-moving',
  path: '/slow-moving',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRecommendationsRoute = PurchaseRecommendationsRouteImport.update({
  id: '/purchase-recommendations',
  path: '/purchase-recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const HighPriorityStockRoute = HighPriorityStockRouteImport.update({
  id: '/high-priority-stock',
  path: '/high-priority-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsItemIdRoute = ItemsItemIdRouteImport.update({
  id: '/items/$itemId',
  path: '/items/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/high-priority-stock': typeof HighPriorityStockRoute
  '/purchase-recommendations': typeof PurchaseRecommendationsRoute
  '/reports': typeof ReportsRoute
  '/slow-moving': typeof SlowMovingRoute
  '/stock-analysis': typeof StockAnalysisRoute
  '/upload': typeof UploadRoute
  '/upload-history': typeof UploadHistoryRoute
  '/items/$itemId': typeof ItemsItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/high-priority-stock': typeof HighPriorityStockRoute
  '/purchase-recommendations': typeof PurchaseRecommendationsRoute
  '/reports': typeof ReportsRoute
  '/slow-moving': typeof SlowMovingRoute
  '/stock-analysis': typeof StockAnalysisRoute
  '/upload': typeof UploadRoute
  '/upload-history': typeof UploadHistoryRoute
  '/items/$itemId': typeof ItemsItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/high-priority-stock': typeof HighPriorityStockRoute
  '/purchase-recommendations': typeof PurchaseRecommendationsRoute
  '/reports': typeof ReportsRoute
  '/slow-moving': typeof SlowMovingRoute
  '/stock-analysis': typeof StockAnalysisRoute
  '/upload': typeof UploadRoute
  '/upload-history': typeof UploadHistoryRoute
  '/items/$itemId': typeof ItemsItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/high-priority-stock'
    | '/purchase-recommendations'
    | '/reports'
    | '/slow-moving'
    | '/stock-analysis'
    | '/upload'
    | '/upload-history'
    | '/items/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/high-priority-stock'
    | '/purchase-recommendations'
    | '/reports'
    | '/slow-moving'
    | '/stock-analysis'
    | '/upload'
    | '/upload-history'
    | '/items/$itemId'
  id:
    | '__root__'
    | '/'
    | '/high-priority-stock'
    | '/purchase-recommendations'
    | '/reports'
    | '/slow-moving'
    | '/stock-analysis'
    | '/upload'
    | '/upload-history'
    | '/items/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HighPriorityStockRoute: typeof HighPriorityStockRoute
  PurchaseRecommendationsRoute: typeof PurchaseRecommendationsRoute
  ReportsRoute: typeof ReportsRoute
  SlowMovingRoute: typeof SlowMovingRoute
  StockAnalysisRoute: typeof StockAnalysisRoute
  UploadRoute: typeof UploadRoute
  UploadHistoryRoute: typeof UploadHistoryRoute
  ItemsItemIdRoute: typeof ItemsItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload-history': {
      id: '/upload-history'
      path: '/upload-history'
      fullPath: '/upload-history'
      preLoaderRoute: typeof UploadHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-analysis': {
      id: '/stock-analysis'
      path: '/stock-analysis'
      fullPath: '/stock-analysis'
      preLoaderRoute: typeof StockAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slow-moving': {
      id: '/slow-moving'
      path: '/slow-moving'
      fullPath: '/slow-moving'
      preLoaderRoute: typeof SlowMovingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-recommendations': {
      id: '/purchase-recommendations'
      path: '/purchase-recommendations'
      fullPath: '/purchase-recommendations'
      preLoaderRoute: typeof PurchaseRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/high-priority-stock': {
      id: '/high-priority-stock'
      path: '/high-priority-stock'
      fullPath: '/high-priority-stock'
      preLoaderRoute: typeof HighPriorityStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$itemId': {
      id: '/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof ItemsItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HighPriorityStockRoute: HighPriorityStockRoute,
  PurchaseRecommendationsRoute: PurchaseRecommendationsRoute,
  ReportsRoute: ReportsRoute,
  SlowMovingRoute: SlowMovingRoute,
  StockAnalysisRoute: StockAnalysisRoute,
  UploadRoute: UploadRoute,
  UploadHistoryRoute: UploadHistoryRoute,
  ItemsItemIdRoute: ItemsItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
